# Generated by Django 6.0 on 2026-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='UPSC CSE', max_length=100)),
                ('year', models.IntegerField()),
                ('general', models.FloatField(help_text='General Category Cutoff')),
                ('ews', models.FloatField(help_text='EWS Cutoff')),
                ('obc', models.FloatField(help_text='OBC Cutoff')),
                ('sc', models.FloatField(help_text='SC Cutoff')),
                ('st', models.FloatField(help_text='ST Cutoff')),
                ('is_official', models.BooleanField(default=True, help_text='Uncheck if this is just an estimate/prediction')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('exam_name', 'year')},
            },
        ),
    ]
