# Generated by Django 6.0 on 2026-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userquestionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerlog',
            name='source_mode',
            field=models.CharField(choices=[('exam', 'Exam'), ('practice', 'Practice')], default='practice', max_length=20),
        ),
    ]
