# Generated by Django 6.0 on 2026-01-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_useranswerlog_source_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerlog',
            name='is_cleared_from_library',
            field=models.BooleanField(default=False),
        ),
    ]
