# Generated by Django 6.0 on 2026-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_useranswerlog_is_cleared_from_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image_url',
            field=models.URLField(blank=True, help_text='Link to diagram or table image', null=True),
        ),
    ]
