# Generated by Django 6.0 on 2026-01-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_question_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
