# Generated by Django 6.0 on 2026-01-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pattern',
            field=models.CharField(choices=[('elim_classical', 'Classical Elimination (Symmetric)'), ('elim_haphazard', 'Haphazard Elimination 🧩'), ('zero_g_statement', 'Zero-G Statement (Only 1/2) 🚀'), ('zero_g_column_2', 'Zero-G Column (2-Col Match)'), ('zero_g_column_3', 'Zero-G Column (3-Col Match) 💀'), ('fifty_fifty', '50-50 Dilemma'), ('assertion_2', 'Assertion (2-Statement)'), ('assertion_3', 'Assertion (3-Statement Mutant) 🧬'), ('one_liner', 'One Liner (Direct MCQ)')], default='one_liner', help_text='The structural pattern of the question.', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('History', 'History'), ('Polity', 'Polity'), ('Geography', 'Geography'), ('Economy', 'Economy'), ('Science & Tech', 'Science & Tech'), ('International Relations', 'International Relations'), ('Environment', 'Environment'), ('Current Affairs', 'Current Affairs'), ('Art & Culture', 'Art & Culture')], max_length=50),
        ),
    ]
