# Generated by Django 6.0 on 2026-01-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_pattern_alter_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerlog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='useranswerlog',
            index=models.Index(fields=['user', 'session_id'], name='quiz_useran_user_id_a8f87d_idx'),
        ),
    ]
